default_profile = "default"

[profiles.default]
user_id = "@daniel:ciahoneypot.com"
url = "https://chat.ciahoneypot.com"

[settings]
log_level = "warn"
reaction_display = true
reaction_shortcode_display = false
read_receipt_send = true
read_receipt_display = true
typing_notice_send = false
typing_notice_display = true

[settings.image_preview]
protocol.type = "kitty"

[settings.sort]
rooms = ["favorite", "lowpriority", "unread", "name"]
members = ["power", "id"]

[layout]
style = "config"

[[layout.tabs]]
window = "#general:ciahoneypot.com"

[[layout.tabs]]
window = "iamb://dms"

[dirs]
cache = "/home/daniel/.cache/iamb/"
logs = "/home/daniel/.local/share/iamb/logs/"
downloads = "/home/daniel/Downloads/"
